import webpack from 'webpack'
import path from 'path'
import HtmlWebpackPlugin from 'html-webpack-plugin'

const port = process.env.PORT || 3000

module.exports = require('./base.config')({
  devtool: 'source-map',
  entry: [
    'react-hot-loader/patch',
    `webpack-dev-server/client?http://localhost:${port}`,
    'webpack/hot/dev-server',
    path.join(process.cwd(), 'src/index.js'),
  ],
  output: {
    filename: '[name].js',
    chunkFilename: '[name].chunk.js',
    publicPath: './',
    hotUpdateChunkFilename: 'hot/hot-update.js',
    hotUpdateMainFilename: 'hot/hot-update.json',
  },
  externals: {
    AppConfig: JSON.stringify(require('../configs/development.json')),
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      children: true,
      minChunks: 2,
      async: true,
    }),
    // inject html template
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: 'index.ejs', // eslint-disable-line no-use-before-define
    }),
    // hot reload
    new webpack.HotModuleReplacementPlugin(),
    // ignore plugin
    new webpack.IgnorePlugin(/webpack-stats\.json$/),
    // define variable to project (global)
    new webpack.DefinePlugin({
      __DEV__: true,
      __DEVTOOLS__: true,
      'process.env': {
        NODE_ENV: JSON.stringify('development'),
      },
    }),
  ],
})
